### ISSUE TITLE
Add option to interrogate redis less frequently  

### ISSUE THREAD

**Issue by MrNghia123** [wyattjoh/rate-limit-redis#18]
There could be a configuration to limit interrogation to redis to e.g. every nth transaction instead of every transaction.

**Comment by wyattjoh** [comment]
This type of interaction would not scale if the application is deployed horizontally.

The point of Redis for this purpose, is to provide a single source of truth, and if we talk to it less frequently, we are no longer trusting Redis with that. If the requests are routed to the same node each time, sure, we don't "really" need to hit Redis each time, but because that isn't guaranteed, I'd recommend not changing the behavior.

You can use a memory based store if you want to reduce database interaction if that's the case.
