### ISSUE TITLE
Make "redis" an optional dependency

### ISSUE THREAD

**Issue by nmoadev** [wyattjoh/rate-limit-redis#21]
I use `rate-limit-redis` with [ioredis](https://github.com/luin/ioredis) as my preferred Redis client library.

While inspecting my projects dependencies I noticed that `rate-limit-redis` has a hard dependency on the `redis` NPM package. From the documentation, `rate-limit-redis` is compatible with either `ioredis` or `redis` 

I suggest making `redis` an optional dependency. This would allow consumers of `rate-limit-redis` to choose which Redis client(s) are installed.

**Comment by wyattjoh** [comment]
It's certainly an interesting idea, but unfortunately, this would mean that every user of `rate-limit-redis` would need to add `redis` or `ioredis` to their dependencies themselves. This could be changed in a new major version, but I'd worry that the default behaviour still provides the easiest installation path.

Maybe a cleaner solution would be to introduce a new package that simply provides the `rate-limit-redis` interface only accepting the client and leave this package as one that includes the hard dependency on `redis`.

Does that sound like an ok solution going forward?

**Comment by samypr100** [comment]
What about maybe using the `peerDependency` strategy?

**Comment by nmoadev** [comment]
@wyattjoh I hadn't considered the impact on existing installs. It's definitely a breaking change that would require a major revision, offering a separate package certainly addresses my concern, but seems harder to maintain over time. For me, the dependency on `redis` isn't a blocker for using the library, so waiting for a major revision is probably the cleanest long-term solution.

@samypr100  I don't think `peerDependency`  quite fits this situation. Since peer dependencies are installed by default.

**Comment by knoxcard2** [comment]
Do what we did here....make the user download ioredis or redis separately, it's not a problem.

https://github.com/tj/connect-redis

**Comment by knoxcard2** [comment]
**Installation**
**npm:**
`npm install redis rate-limit-redis`

**Yarn:**
`yarn add redis rate-limit-redis`

**Comment by gamemaker1** [comment]
Hi,

I recently helped out with the Typescript rewrite (PR #43), which also changes how the store interacts with Redis - v3.0.0 will accept the `sendCommand` option instead of the `client` option. `sendCommand` is a (sync/async) function that takes the raw command as an array of `string`s and returns the `number` or `string` response from redis. This makes the store compatible with all clients that have a public method to send raw commands to redis.

This means this package has no dependency on a particular Redis client, however, we could still add popular clients like `redis`, `ioredis`, etc. as `optionalDependencies`.

Let me know what you think.
