### ISSUE TITLE
'passIfNotConnected' option is not compatible with ioredis client

### ISSUE THREAD

**Issue by JamesMGreene** [wyattjoh/rate-limit-redis#34]
I love the idea of the `passIfNotConnected` option that was recently added in https://github.com/wyattjoh/rate-limit-redis/pull/29

However, it is based on the `redis` ("node-redis") client implementation of the `client.connected` Boolean, which is not compatible with the `ioredis` client.

In `ioredis`, they seem to use the following complex set of checks for determining if the client is connected (e.g. [source example](https://github.com/luin/ioredis/blob/0327ef5a57481042d3f7d306917f55ef04f3a6cc/lib/redis/index.ts#L291-L295)):

```js
if (
  this.status === "connecting" ||
  this.status === "connect" ||
  this.status === "ready"
) {
  reject(new Error("Redis is already connecting/connected"));
  return;
}
```

**Comment by JamesMGreene** [comment]
I haven't tried it myself but this may be a valid workaround to those using `ioredis`:

```js
const Redis = require("ioredis");
const client = new Redis(/* ... options ... */);

//
// WORKAROUND
//
client.on('connect', function () { client.connected = true; });
client.on('close', function () { client.connected = false; });
```

**Comment by luin** [comment]
Hi, I'm the author of ioredis (and contributor of node_redis) and happened to see this issue. Thank @JamesMGreene for pointing this out!

I think to better reflect the intent, we should check `.ready` instead of `.connected` as when `.connected` is true, the client may be not ready to send/receive commands.

The equivalent of `.ready` in ioredis is `.status === 'ready'`. So to support ioredis, the easiest change would be changing the following code in redis-store.js:

```javascript
if (!options.client.connected && options.passIfNotConnected) {
```

To:

```javascript
const clientConnected =
  options.client.status == 'ready' || // ioredis
  options.client.ready; // node_redis
if (!clientConnected && options.passIfNotConnected) {
```

> I haven't tried it myself but this may be a valid workaround to those using ioredis:

Looks good to me. To be more complete:

```javascript
const Redis = require("ioredis");
const client = new Redis(/* ... options ... */);
client.connected = false;
client.ready = false;

client.on('connect', function () { client.connected = true; });
client.on('ready', function () { client.ready = true; });
client.on('close', function () {
  client.connected = false;
  client.ready = false;
});

```

**Comment by wyattjoh** [comment]
Thanks for the suggestions! I've been meaning to get back to this package to improve it (hopefully with a rewrite to Typescript!). I will likely be making a release soon that will deprecate the current mechanism of automatically creating a Redis client, and instead requiring a already created client to be passed to it to use. Happy for any feedback!

**Comment by gamemaker1** [comment]
Hi,

I recently helped out with the Typescript rewrite (PR #43), which also changes how the store interacts with Redis - v3.0.0 will accept the [`sendCommand`](https://github.com/wyattjoh/rate-limit-redis#sendcommand) option instead of the `client` option. `sendCommand` is a (sync/async) function that takes the raw command as an array of `string`s and returns the `number` or `string` response from redis. This makes the store compatible with all clients that have a public method to send raw commands to redis.

This means this package has no dependency on a particular Redis client, and users are responsible for handling connection via their preferred client. So the `passIfNotConnected` option has been removed in v3.0.0.

Please let me know if there is something we can improve with this implementation.
