### ISSUE TITLE
Limit API Key instead of IP

### ISSUE THREAD

**Issue by pgamerxdev** [wyattjoh/rate-limit-redis#36]
Hey there, I want to limit API key rather than IP. 
is it possible?

**Comment by wyattjoh** [comment]
This is designed as an extension to the https://github.com/nfriedly/express-rate-limit package, and therefore is designed to work with IP addresses by default.

You could explore using https://github.com/nfriedly/express-rate-limit#keygenerator to return an api key instead of the ip here from the header if you like, best of luck!

**Comment by pgamerxdev** [comment]
> This is designed as an extension to the https://github.com/nfriedly/express-rate-limit package, and therefore is designed to work with IP addresses by default.
> 
> You could explore using https://github.com/nfriedly/express-rate-limit#keygenerator to return an api key instead of the ip here from the header if you like, best of luck!

Thanks
