### ISSUE TITLE
rate-limit-redis works with `redis` and not with `ioredis`

### ISSUE THREAD

**Issue by guillaumemeyer** [wyattjoh/rate-limit-redis#38]
We're migrating from the `redis` module to `ioredis`.
Once migrated the `rate-limit-redis` module stops working and generates an error message:
`redis client is not connected, rate-limit-redis disabled!`
Despite the fact the client is actually connected.

The following code works:
```js
const Redis = require('redis')
const redisClient = Redis.createClient({
  host: env.vars.REDIS_HOST,
  port: env.vars.REDIS_PORT,
  db: env.vars.REDIS_DB,
  password: env.vars.REDIS_SECRET_KEY,
  tls: env.vars.REDIS_TLS,
  connect_timeout: env.vars.REDIS_TIMEOUT,
  prefix: env.vars.REDIS_KEYS_PREFIX
})
```

While this one doesn't work:
```js
const IoRedis = require('ioredis')
const redisClient = new IoRedis({
  host: env.vars.REDIS_HOST,
  port: env.vars.REDIS_PORT,
  db: env.vars.REDIS_DB,
  password: env.vars.REDIS_SECRET_KEY,
  tls: env.vars.REDIS_TLS,
  connectTimeout: env.vars.REDIS_TIMEOUT,
  keyPrefix: env.vars.REDIS_KEYS_PREFIX
})
```

Once the redis client is created, it is used as a new RedisStore:
```js
const rateLimiter = rateLimit({
    ...
    store: new RedisStore({
      expiry: 60,
      resetExpiryOnChange: false,
      prefix: `ratelimiter:tier${tierIndex + 1}:`,
      client: redisClient,
      passIfNotConnected: true // If Redis is not connected, let the request succeed as failover
    })
  })
})
```

**Comment by gamemaker1** [comment]
Hi,

I recently helped out with the Typescript rewrite (PR #43), which also changes how the store interacts with Redis - v3.0.0 will accept the [`sendCommand`](https://github.com/wyattjoh/rate-limit-redis#sendcommand) option instead of the `client` option.

`sendCommand` is a (sync/async) function that takes the raw command as an array of `string`s and returns the `number` or `string` response from redis. This makes the store compatible with all clients that have a public method to send raw commands to redis.

Please do take a look at [the readme for an example](https://github.com/wyattjoh/rate-limit-redis#examples) of using the store with an IORedis client.
