### ISSUE TITLE
ioredis example shows the incorrect syntax for sendCommand

### ISSUE THREAD

**Issue by kai-sm** [wyattjoh/rate-limit-redis#70]
### Description

Bug:
<img width="780" alt="Screen Shot 2022-03-09 at 10 02 25 AM" src="https://user-images.githubusercontent.com/90229797/157324509-17a2eda9-837f-47e6-a035-c1660c27cc0b.png">

Expected:
Spread operator to be used
```
    sendCommand: (...args: string[]) => client.call(...args),
```

### Library version

3.0.0

### Node version

16.14.0

### Typescript version (if you are using it)

3.9.10

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @kai-sm,

Thanks for reporting this issue :D

This issue was fixed in https://github.com/wyattjoh/rate-limit-redis/pull/48, but a new release has not been created - so the readme page on npm has still not been updated. When a new release is made, the readme on npm will automatically include the new changes.

**Comment by wyattjoh** [comment]
I'll cut a patch release now!

**Comment by wyattjoh** [comment]
3.0.1 is live and has updated the documentation!
